---
#######################
#    Drives & Disk    #
#######################
partitions_unit: "%"
partitions: 
  - device: /dev/sdb
    number: 1
    mountpoint: /data/standard
    fstype: ext4
    start: 0
    size: 75
    
  - device: /dev/sdb
    number: 2
    mountpoint: /data/backup
    fstype: ext4
    start: 75
    size: 25

  - device: /dev/sdc
    number: 1
    mountpoint: /data/premium
    fstype: ext4
    start: 0
    size: 100

backups_script_dir: /var/backups
backups:
  - name: premium_partition
    source: /data/premium/
    destination: /data/backup
    logdir: /var/log/backups/
    rsync_option: "vd"
    cron:
      minute: "*/5"
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"

#######################
#  Kubernetes roles   #
#######################
kubernetes_role: master
