---

- hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - ping:
      tags:
        - always

- hosts: all
  gather_facts: false
  name: Prepare server & Manage user
  roles:
    - roles/users
    - roles/hardening
  tags: 
    - hardening

- hosts: caas
  gather_facts: false
  name: Kubernetes Single Node Cluster
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
    - roles/kubernetes_configuration
  post_tasks:
    - include_tasks: tasks/kubernetes_administrator.yml
      with_items: "{{ kubernetes_admin }}"
  tags:
    - kubernetes
    - kubernetes::cluster

- hosts: caas
  gather_facts: false
  name: Deploy applications
  roles:
    - roles/applications
  tags:
    - kubernetes 
    - kubernetes::apps
