---

- hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - ping:
      tags:
        - always

- hosts: all
  gather_facts: false
  name: Prepare server & Manage user
  roles:
    - roles/prepare_server
    - roles/manage_users

- hosts: all
  gather_facts: false
  name: Docker Node
  become: true
  roles:
    - geerlingguy.docker
