---
- hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - ping:
      tags:
        - always

- hosts: all
  gather_facts: false
  name: Prepare server & Manage user
  roles:
    - roles/hardening
  tags:
    - hardening

- hosts: nfs
  gather_facts: false
  name: NFS server
  become: true
  roles:
    - geerlingguy.nfs
  tags:
    - nfs

- hosts: caas
  gather_facts: false
  name: Single node raw Kubernetes cluster
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.helm
    - geerlingguy.kubernetes
  post_tasks:
    - include_tasks: tasks/kubernetes_administrator.yml
      with_items: "{{ kubernetes_admin }}"
    - include_tasks: tasks/helm_diff.yml
  tags:
    - kubernetes
    - kubernetes::cluster

- hosts: caas
  gather_facts: false
  name: Kubernetes Core
  become: true
  roles:
    - roles/kube-core
  tags:
    - kubernetes
    - kubernetes::core

- hosts: caas
  gather_facts: false
  name: Kubernetes Data
  become: true
  roles:
    - roles/kube-data
  tags:
    - kubernetes
    - kubernetes::data

- hosts: caas
  gather_facts: false
  name: Kubernetes IAM
  become: true
  roles:
    - roles/kube-iam
  tags:
    - kubernetes
    - kubernetes::iam


- hosts: caas
  gather_facts: false
  name: Kubernetes Gitops
  become: true
  roles:
    - roles/kube-gitops
  tags:
    - kubernetes
    - kubernetes::gitops

- hosts: caas
  gather_facts: false
  name: MBCaaS Portal
  become: true
  tasks:
    - include_tasks: tasks/mbcaas-portal.yml
  tags:
    - kubernetes
    - kubernetes::portal
