bobineshowroom:
  #
  # Meta
  #
  name: bobineshowroom
  namespace: default
  deployed: true

  #
  # App
  #
  pod_volumes: []

  containers:
    - name: bobineshowroom
      image: ghcr.io/bricemichalski/bobine-showroom:master
      imagePullPolicy: Always
      ports:
      - containerPort: 80
  
  service_ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  
  tls: []

  ingress_rules:
    - host: bobineshowroom.mbcaas.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: bobineshowroom
              port:
                number: 80 
