whoami:
  deployed: true

  #
  # Meta
  #
  name: whoami
  namespace: default

  #
  # Middleware 
  #
  traefik_middleware: 
    - "admin-auth"

  #
  # App
  #
  pod_volumes: []

  containers:
    - name: whoami
      image: containous/whoami
      ports:
      - containerPort: 80
  
  service_ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  
  tls: 
    - hosts:
      - whoami.mbcaas.com
      secretName: whoami.mbcaas.com-cert
      
  ingress_rules:
    - host: whoami.mbcaas.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: whoami
              port:
                number: 80