---
#######################
#    Drives & Disk    #
#######################
hard_drives:
  - path: /dev/sda
    mountpoint: /data

#######################
#     Usual tips      #
#######################
usual_apt_package:
  - git
  - jq
  - curl
  - nmap
  - net-tools
  - python3-pip

usual_pip_package:
  - openshift
  - PyYAML
