helmDefaults:
  timeout: 600
  force: false
  createNamespace: false

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:

- name: home-assistant
  namespace: home
  chart: bitnami/nginx
  missingFileHandler: Warn
  version: 15.5.1
  values:
  - modules/home-assistant.yaml
  secrets:
  - ./secrets.sops.yaml

- name: frigate
  namespace: home
  chart: bitnami/nginx
  missingFileHandler: Warn
  version: 15.5.1
  values:
  - modules/frigate.yaml
  secrets:
  - ./secrets.sops.yaml