---
roles:
  - name: geerlingguy.docker
    version: 3.1.2

  - name: geerlingguy.helm
    version: 1.0.1

  - name: geerlingguy.kubernetes
    version: 6.0.0

  - name: geerlingguy.nfs
    version: 2.0.0

collections:
  - name: community.general
    version: 3.4.0

  - name: community.kubernetes
    version: 2.0.1