name: home-dev
box: bento/ubuntu-20.04
ip: 192.168.50.10
memory: 8096
cpu: 4
disk_directory: "/home/brice_michalski/Perso/.vagrantdisk"
disks:
  - name: second
    size: 40
    port: 2
  - name: third
    size: 10
    port: 3
