---

- name: Install longhorn
  become: true
  block:

    - name: Create longhorn namespace
      kubernetes.core.k8s:
        name: "longhorn-system"
        api_version: v1
        kind: Namespace
        state: present
        wait: true

    - name: Install longhorn helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "{{ longhorn_charts_url }}"
    
    # - name: update repo
    #   command:
    #     cmd: helm repo update

    - name: Install longhorn helm charts
      kubernetes.core.helm:
        release_namespace: "{{ kube_core_namespace }}"
        name: longhorn
        chart_version: "{{ longhorn_version }}"
        chart_ref: longhorn/longhorn
        update_repo_cache: True
        values: "{{ lookup('template', 'longhorn.yaml.j2') | from_yaml }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::core
