---
- name: Traefik Middleware cloudflare ip whitelist
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'exploitation/cloudflare-ip-whiteist-mdw.yml') }}"
    wait: yes
  when: enable_cloudflare_ip_whitelist
  
- name: Traefik Middleware admin auth
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'exploitation/admin-auth-mdw.yml') }}"
    wait: yes

- name: Deploy traefik dashboard
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'traefik/dashboard.yaml.j2') }}"
    wait: yes

