---
- name: Traefik Middleware cloudflare ip whitelist
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'exploitation/cloudflare-ip-whiteist-mdw.yml.j2') }}"
    wait: yes
  when: enable_cloudflare_ip_whitelist
  
- name: Traefik Middleware admin auth
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'exploitation/admin-auth-mdw.yml.j2') }}"
    wait: yes

- name: Deploy traefik dashboard
  kubernetes.core.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'traefik/dashboard.yaml.j2') }}"
    wait: yes

- name: Deploy whoami app
  vars: 
    app: "{{ whoami }}"
  import_role:
    name: roles/applications
    tasks_from: handle_app

- name: Install Portainer
  become: true
  block:

    - name: Install portainer repository
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: https://portainer.github.io/k8s/

    - name: Install portainer charts
      kubernetes.core.helm:
        name: portainer
        chart_ref: portainer/portainer
        release_namespace: "{{ kube_operable_namespace }}"
        values: "{{ lookup('template', 'exploitation/portainer.yml.j2') | from_yaml }}"
        wait: yes

    - name: Portainer ingress
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'exploitation/portainer-ingress.yml.j2') }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::monitoring


- name: Install MBCaaS portal
  become: true
  block:

    - name: Install k8s-at-home repository
      kubernetes.core.helm_repository:
        name: k8s-at-home
        repo_url: https://k8s-at-home.com/charts/

    - name: Install homer portal
      kubernetes.core.helm:
        name: homer
        chart_ref: k8s-at-home/homer
        release_namespace: "{{ kube_operable_namespace }}"
        values: "{{ lookup('template', 'exploitation/portal.yml.j2') | from_yaml }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::portal