---
- name: Generate backup configuration
  become: true
  block:
    - name: Assert backups script dir exist
      file:
        path: "{{ backups_script_dir }}"
        state: directory

    - name: Assert backup destination exist
      file:
        path: "{{ backup.destination }}"
        state: "directory"

    - name: Assert backup logs dir exist
      file:
        path: "{{ backup.logdir }}"
        state: "directory"

    - name: Generate backup scripts
      template:
        src: "backup.sh.j2"
        dest: "{{ backups_script_dir }}/{{ backup.name | replace('-','_') }}_backup.sh"
        owner: root
        group: root
        mode: 0700

    - name: Generate crontab entry
      cron:
        name: "{{ backup.name | replace('-','_') }}"
        minute: "{{ backup.cron.minute }}"
        hour: "{{ backup.cron.hour }}"
        day: "{{ backup.cron.day }}"
        month: "{{ backup.cron.month }}"
        weekday: "{{ backup.cron.weekday }}"
        user: root
        job: "{{ backups_script_dir }}/{{ backup.name | replace('-','_') }}_backup.sh"
  tags:
    - hardening
    - hardening::backup
