---
- name: "Manage {{ disk.name }}"
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ playbook_dir }}/../kubeconfig"
  block:
    - name: unmount partition
      ansible.posix.mount:
        path: "{{ hard_drive.mountpoint }}"
        state: unmounted

    - name: Register disk letter
      file:
        path: "{{ hard_drive.path }}"
        state: file
      register: disk

    - name: Update primary partition for disk
      parted:
        align: optimal
        device: "{{ disk.path }}"
        part_end: "100%"
        resize: true
        number: 1
        state: present
        label: msdos
      register: parted

    - name: check ext4 filesystem
      command:
        cmd: "e2fsck -f -y {{ disk.path }}1"

    - name: update ext4 filesystem
      filesystem:
        fstype: ext4
        dev: "{{ disk.path }}1"
        resizefs: true

    - name: get disk uuid
      gather_facts:

    - name: mount disk by uuid
      mount:
        path: "{{ hard_drive.mountpoint }}"
        src: UUID={{ ansible_facts['devices'][( disk.path | basename)]['partitions'][( disk.path | basename) ~ '1']['uuid'] }}
        fstype: ext4
        opts: 'defaults,nofail'
        dump: '1'
        passno: '2'
        state: mounted
  tags:
    - hardening
    - hardening::disk