---
- name: "Manage partition"
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ playbook_dir }}/../kubeconfig"
  block:

    - name: Partitions formatting
      parted:
        device: "{{ partition.device }}"
        part_end: "{{ partition.size }}"
        resize: true
        number: "{{ partition.number }}"
        fs_type: "{{ partition.fstype }}"
        state: present

    - name: Update filesystem
      filesystem:
        fstype: "{{ partition.fstype }}"
        dev: "{{ partition.device }}{{ partition.number }}"
        resizefs: true

    - name: Mount partition
      mount:
        path: "{{ partition.mountpoint }}"
        src: "{{ partition.device }}{{ partition.number }}"
        fstype: "{{ partition.fstype }}"
        opts: 'defaults,nofail'
        state: mounted
    
  tags:
    - hardening
    - hardening::partition