---
ldap_user_manager:
  deployed: true

  #
  # Meta
  #
  name: ldap-user-manager
  namespace: "{{ kube_iam_namespace }}"

  #
  # Middleware
  #
  traefik_middleware: ""

  #
  # App
  #
  pod_volumes: []

  containers:
    - name: ldap-user-manager
      image: wheelybird/ldap-user-manager:oldcookies
      ports:
        - containerPort: 80
      env:
        - name: SERVER_HOSTNAME
          value: 12.168.50.20
        - name: ORGANISATION_NAME
          value: mbcaas
        - name: SITE_NAME
          value: MBCaaS
        - name: LDAP_URI
          value: ldap://openldap-openldap-stack-ha
        - name: LDAP_BASE_DN
          value: dc=mbcaas,dc=com
        - name: LDAP_ADMIN_BIND_DN
          value: cn=admin,dc=mbcaas,dc=com
        - name: LDAP_ADMIN_BIND_PWD
          valueFrom:
            secretKeyRef:
              name: ldap-credential
              key: LDAP_ADMIN_PASSWORD
        - name: LDAP_ADMINS_GROUP
          value: admins
        - name: LDAP_REQUIRE_STARTTLS
          value: "false"
        - name: LDAP_IGNORE_CERT_ERRORS
          value: "true"
        - name: NO_HTTPS
          value: "true"

  service_ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

  tls:
    - hosts:
        - "{{ user_manager_domain }}"
      secretName: "{{ user_manager_domain }}-tls"

  ingress_rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ldap-user-manager
                port:
                  number: 80
