---
phpredisadmin:
  deployed: true

  #
  # Meta
  #
  name: redis-admin-ui
  namespace: "{{ kube_data_namespace }}"

  #
  # Middleware
  #
  traefik_middleware: []

  #
  # App
  #
  pod_volumes: []

  containers:
    - name: phpredisadmin
      image: erikdubbelboer/phpredisadmin
      ports:
        - containerPort: 80
      env: 
        - name: REDIS_1_HOST
          value: redis-master
        - name: REDIS_1_NAME
          value: redis-master
        - name: REDIS_1_PORT
          value: "6379"
        - name: REDIS_1_AUTH
          value: "{{ redis_admin_password }}"
        - name: ADMIN_USER
          value: brice_michalski
        - name: ADMIN_PASS
          value: "{{ redis_admin_password }}"

  service_ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

  tls:
    - hosts:
        - "{{ redis_admin_domain }}"
      secretName: "{{ redis_admin_domain }}-tls"

  ingress_rules:
    - host: "{{ redis_admin_domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-admin-ui
                port:
                  number: 80
