---

- name: 'Create user accounts'
  user:
    name: "{{ user.key }}"
    append: true
    group: "{{ user.value.group | default(omit) }}"
    groups: "{{ user.value.groups | default(omit) }}"
    uid: "{{ user.value.uid | default(omit) }}"
    state: 'present'
  become: true

- name: 'Put ssh key in user ssh folder'
  authorized_key:
    user: "{{ user.key }}"
    state: 'present'
    key: "{{ user.value.public_key }}"
    exclusive: true
  when: user.value.public_key is defined
  become: true

- name: "Grant admin rights to {{ user.key }} via sudo without password"
  template:
    src: 'sudoer_user.j2'
    dest: "/etc/sudoers.d/{{ user.key }}"
    owner: 'root'
    group: 'root'
    mode: '0440'
  when: user.value.admin is defined and user.value.admin
  become: true

- name: "Remove admin rights to {{ user.key }} via sudo without password"
  file:
    path: "/etc/sudoers.d/{{ user.key  }}"
    state: "absent"
  when: user.value.admin is not defined or not user.value.admin
  become: true
