---

#######################
#  K8S Customization  #
#######################

kubernetes_admin:
  - brice_michalski
  - vagrant

#######################
#     K8S  Network    #
#######################

kube_ip_range_start: 192.168.50.20
kube_ip_range_end: 192.168.50.30