---
#######################
#  NFS Configuration  #
#######################
nfs_exports: 
  - "/data/standard 127.0.0.1(rw,sync,no_root_squash)"
  - "/data/premium 127.0.0.1(rw,sync,no_root_squash)"   

nfs_provisioner_charts_value:
  nfs:
    server: "127.0.0.1"
    path: "/data"
  storageClass:
    create: true

    # Set a provisioner name. If unset, a name will be generated.
    # provisionerName:

    # Set StorageClass as the default StorageClass
    # Ignored if storageClass.create is false
    defaultClass: true

    # Set a StorageClass name
    # Ignored if storageClass.create is false
    name: nfs-client

    # Allow volume to be expanded dynamically
    allowVolumeExpansion: true

    # Method used to reclaim an obsoleted volume
    reclaimPolicy: Retain

    # When set to false your PVs will not be archived by the provisioner upon deletion of the PVC.
    archiveOnDelete: true

    # If it exists and has 'delete' value, delete the directory. If it exists and has 'retain' value, save the directory.
    # Overrides archiveOnDelete.
    # Ignored if value not set.
    onDelete:

    # Specifies a template for creating a directory path via PVC metadata's such as labels, annotations, name or namespace.
    # Ignored if value not set.
    pathPattern:

    # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
    accessModes: ReadWriteOnce

    # Storage class annotations
    annotations: {}