---

- name: Create data namespace
  kubernetes.core.k8s:
    name: "{{ kube_iam_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: true

- name: Install open ldap
  block:

    - name: Install openldap repos
      kubernetes.core.helm_repository:
        name: helm-openldap
        repo_url: https://jp-gouin.github.io/helm-openldap/

    - name: Deploy ldap-credential secret
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'ldapSecret.yml.j2') }}"

    - name: Install openldap
      kubernetes.core.helm:
        name: openldap
        chart_ref: helm-openldap/openldap-stack-ha
        release_namespace: "{{ kube_iam_namespace }}"
        values: "{{ lookup('template', 'openldap.yml.j2') | from_yaml }}"
        wait: yes

    - name: deploy ui
      vars:
        app: "{{ ldap_user_manager }}"
      import_role:
        name: roles/kube-apps
        tasks_from: custom

  tags:
    - kubernetes
    - kubernetes::iam
