---
- name: Create user group
  group:
    name: "{{ user.value.group }}"
    gid: "{{ user.value.gid }}"
    state: present
  become: true

- name: 'Create user accounts'
  user:
    name: "{{ user.key }}"
    append: true
    group: "{{ user.value.group }}"
    groups: "{{ user.value.groups }}"
    uid: "{{ user.value.uid }}"
    state: 'present'
    shell: "/bin/bash"
  become: true

- name: 'Put ssh key in user ssh folder'
  authorized_key:
    user: "{{ user.key }}"
    state: 'present'
    key: "{{ public_key }}"
  loop: "{{ user.value.public_keys }}"
  loop_control:
    loop_var: public_key
  when: user.value.public_keys is defined
  become: true

- name: "Grant admin rights to {{ user.key }} via sudo without password"
  template:
    src: 'sudoer_user.j2'
    dest: "/etc/sudoers.d/{{ user.key }}"
    owner: 'root'
    group: 'root'
    mode: '0440'
  when: user.value.admin is defined and user.value.admin
  become: true

- name: "Remove admin rights to {{ user.key }} via sudo without password"
  file:
    path: "/etc/sudoers.d/{{ user.key  }}"
    state: "absent"
  when: user.value.admin is not defined or not user.value.admin
  become: true
