---
#######################
#    Drives & Disk    #
#######################
hard_drives:
  - path: /dev/sda
    mountpoint: /data

#######################
#  Kubernetes roles   #
#######################
kubernetes_role: master

