---
#######################
#    Drives & Disk    #
#######################
partitions_unit: "%"
partitions:
  - device: /dev/sda
    number: 1
    mountpoint: /data/longhorn
    fstype: ext4
    start: 0
    size: 100

  - device: /dev/sdb
    number: 1
    mountpoint: /data/nfs
    fstype: ext4
    start: 0
    size: 100

nfs_exports:
  - "/data/nfs 127.0.0.1(rw,sync,no_root_squash)"

#######################
#  Kubernetes roles   #
#######################
kubernetes_role: master
