---
#######################
#    Drives & Disk    #
#######################
partitions: 
  - device: /dev/sda
    number: 1
    mountpoint: /data
    fstype: ext4
    size: 100%
    
#######################
#  Kubernetes roles   #
#######################
kubernetes_role: master

