---

- name: Create data namespace
  kubernetes.core.k8s:
    name: "{{ kube_data_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: true

- name: Deploy MYSQL
  include_tasks: mysql.yml
