---
- name: Create Local Persistant Volume
  become: true 
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'pv.yaml.j2') }}"
  loop: "{{ kubernetes_local_volumes }}"
  loop_control:
    loop_var: volume
  tags:
    - kubernetes
    - kubernetes::volumes

- name: Install MetalLb
  become: true
  block:
    - name: Check if strictARP is enable
      shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/' | kubectl diff -f - -n kube-system"
      failed_when: false
      changed_when: false
      register: strict_arp_enable

    - name: Apply strict ARP
      shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/' | kubectl apply -f - -n kube-system"
      when: strict_arp_enable.rc != 0

    - name: Create custom manifest dir
      file:
        path: /etc/kubernetes/custom_manifests
        state: directory
        
    - name: Download MetalLB namespace manifest
      get_url:
        url: "{{ metallb.namespace }}"
        dest: "{{ custom_manifest_location }}/metallb-namespace.yaml"
        mode: '0664'

    - name: Apply MetalLB namespace manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/metallb-namespace.yaml"

    - name: Download MetalLB manifest
      get_url:
        url: "{{ metallb.install}}"
        dest: "{{ custom_manifest_location }}/metallb.yaml"
        mode: '0664'

    - name: Apply MetalLB manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/metallb.yaml"

    - name: Deploy MetalLB configuration
      template:
        src: "matallb-config.yaml.j2"
        dest: "{{ custom_manifest_location }}/metallb-config.yaml"
        owner: root
        group: root
        mode: 0600

    - name: Apply MetalLB config manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/metallb-config.yaml"
  tags:
    - kubernetes
    - kubernetes::metallb


- name: Install nginx ingress controller
  become: true
  block:
    - name: Download nginx ingress controller manifest
      get_url:
        url: "{{ nginx_ingress_controller }}"
        dest: "{{ custom_manifest_location }}/nginx-ingress-controller.yaml"
        mode: '0664'

    - name: Apply nginx ingress controller manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/nginx-ingress-controller.yaml"
  tags:
    - kubernetes
    - kubernetes::ingress-controller

- name: Install external dns
  become: true
  block:
    - name: Deploy external dns manifest
      template:
        src: "external-dns.yaml.j2"
        dest: "{{ custom_manifest_location }}/external-dns.yaml"
        owner: root
        group: root
        mode: 0600

    - name: Apply external dns manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/external-dns.yaml"
  tags:
    - kubernetes
    - kubernetes::external-dns

- name: Install Cert-manager
  become: true
  block:
    - name: Download cert-manager manifest
      get_url:
        url: "{{ cert_manager.install }}"
        dest: "{{ custom_manifest_location }}/cert-manager.yaml"
        mode: '0664'

    - name: Apply cert-manager manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/cert-manager.yaml"

    - name: Deploy cert-manager cloudflare secret
      k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'cert-manager-cloudflare-secret.yaml.j2') }}"

    - name: Deploy cert-manager cloudflare issuer
      k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'cert-manager-cloudflare-issuer.yaml.j2') }}"
      retries: 3
      delay: 5

  tags:
    - kubernetes
    - kubernetes::cert-manager