---

- name: Storage configuration
  include_tasks: storage.yml

- name: Networking configuration
  include_tasks: networking.yml

- name: Monitoring configuration
  include_tasks: monitoring.yml

- name: Production spécific configuration
  include_tasks: production.yml
  when: production_environment

- name: Wait 3 minutes to allow time for the container to start
  run_once: true
  pause:
    minutes: 3