- name: Install MetalLb
  become: true
  block:
    - name: Check if strictARP is enable
      shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/' | kubectl diff -f - -n kube-system"
      failed_when: false
      changed_when: false
      register: strict_arp_enable

    - name: Apply strict ARP
      shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/' | kubectl apply -f - -n kube-system"
      when: strict_arp_enable.rc != 0

    - name: Create custom manifest dir
      file:
        path: "{{ custom_manifest_location }}"
        state: directory
        
    - name: Download MetalLB namespace manifest
      get_url:
        url: "{{ metallb_namespace_url }}"
        dest: "{{ custom_manifest_location }}/metallb-namespace.yaml"
        mode: '0664'

    - name: Apply MetalLB namespace manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/metallb-namespace.yaml"

    - name: Download MetalLB manifest
      get_url:
        url: "{{ metallb_manifest_url }}"
        dest: "{{ custom_manifest_location }}/metallb.yaml"
        mode: '0664'

    - name: Apply MetalLB manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/metallb.yaml"

    - name: Deploy MetalLB configuration
      template:
        src: "metallb-config.yaml.j2"
        dest: "{{ custom_manifest_location }}/metallb-config.yaml"
        owner: root
        group: root
        mode: 0600

    - name: Apply MetalLB config manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/metallb-config.yaml"
  tags:
    - kubernetes
    - kubernetes::metallb


- name: Install nginx ingress controller
  become: true
  block:
    - name: Download nginx ingress controller manifest
      get_url:
        url: "{{ nginx_ingress_controller }}"
        dest: "{{ custom_manifest_location }}/nginx-ingress-controller.yaml"
        mode: '0664'

    - name: Apply nginx ingress controller manifest to the cluster.
      k8s:
        state: present
        src: "{{ custom_manifest_location }}/nginx-ingress-controller.yaml"
  tags:
    - kubernetes
    - kubernetes::ingress-controller