---

- name: NFS storage provisionner rbac
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'nfs-storage-rbac.yml.j2') }}"

- name: NFS storage provisionner deployment
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'nfs-storage-deployment.yml.j2') }}"


- name: NFS storage provisionner storage class
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'nfs-storage-class.yml.j2') }}"