---

#######################
#  K8S Customization  #
#######################

kubernetes_admin:
  - brice_michalski

#######################
#     K8S  Network    #
#######################

kube_ip_range_start: 192.168.1.210
kube_ip_range_end: 192.168.1.240